# Generated by Django 3.2.8 on 2021-10-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='wants_emails',
            field=models.BooleanField(default=False),
        ),
    ]
