# Generated by Django 3.2.8 on 2021-10-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reciever_phone',
            new_name='receiver_phone',
        ),
    ]
