# Generated by Django 3.2.8 on 2021-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_reciever_phone_order_receiver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='actual_delivery',
            field=models.CharField(default='now', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='now', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(default='now', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Toronto', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.CharField(default='now', max_length=60),
        ),
        migrations.AddField(
            model_name='order',
            name='postal',
            field=models.CharField(default='now', max_length=30),
        ),
    ]
