# Generated by Django 3.2.8 on 2021-10-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20211019_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='actual_delivery',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='apartment',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal',
            field=models.CharField(max_length=30),
        ),
    ]
