# Generated by Django 3.2.8 on 2021-10-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wants_emails',
            field=models.BooleanField(default=False),
        ),
    ]
