# Generated by Django 3.2.8 on 2021-10-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20211019_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_without_tax',
            field=models.FloatField(default=0),
        ),
    ]
