# Generated by Django 3.2.8 on 2021-10-20 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_total_without_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='user',
        ),
    ]
