# Generated by Django 3.2.8 on 2021-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_remove_orderproduct_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expected_delivery',
            field=models.CharField(default='TBA', max_length=60),
        ),
    ]
