# Generated by Django 3.2.8 on 2021-10-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_expected_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_points_used',
            field=models.IntegerField(default=0),
        ),
    ]
