# Generated by Django 3.2.8 on 2021-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_flowers_inside'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flowers_inside',
            field=models.ManyToManyField(blank=True, to='products.SingleFlower'),
        ),
    ]
