# Generated by Django 3.2.8 on 2021-10-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_times_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleflower',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
