# Generated by Django 3.2.8 on 2021-11-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_reviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='displayed_name',
            field=models.CharField(default='John', max_length=30),
        ),
    ]
