# Generated by Django 3.2.8 on 2021-11-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_reviewrating_displayed_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='displayed_name',
        ),
        migrations.AddField(
            model_name='reviewrating',
            name='display_name',
            field=models.CharField(blank=True, default='Anonymous', max_length=30),
        ),
    ]
