# Generated by Django 3.2.8 on 2021-11-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20211031_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='display_name',
            field=models.CharField(max_length=30),
        ),
    ]
